import argparse
import hashlib
import html
import json
import re
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.error import URLError
from urllib.request import Request, urlopen


MINECRAFT_NEWS_URL = "https://www.minecraft.net/en-us/articles"
VERSION_MANIFEST_URL = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json"
PROFILE_URL = "https://api.mojang.com/users/profiles/minecraft/Notch"
SESSION_URL = "https://sessionserver.mojang.com/session/minecraft/profile/069a79f444e94726a5befca90e38aaf5"
CACHE_SECONDS = 30
_cache = {"created": 0.0, "payload": b""}


def fetch_json(url):
    request = Request(url, headers={"User-Agent": "PCL-Miku-Realtime-Home/1.0"})
    with urlopen(request, timeout=8) as response:
        return json.loads(response.read().decode("utf-8"))


def fetch_text(url):
    request = Request(url, headers={"User-Agent": "PCL-Miku-Realtime-Home/1.0"})
    with urlopen(request, timeout=8) as response:
        return response.read().decode("utf-8", "replace")


def api_status(label, url, detail, parser=None):
    started = time.perf_counter()
    try:
        payload = fetch_json(url)
        elapsed = int((time.perf_counter() - started) * 1000)
        value = parser(payload) if parser else "响应正常"
        return {"label": label, "state": "ONLINE", "detail": f"{detail} · {value} · {elapsed} ms"}
    except Exception as exc:
        return {"label": label, "state": "OFFLINE", "detail": f"{detail} · {type(exc).__name__}"}


def collect_news():
    try:
        page = fetch_text(MINECRAFT_NEWS_URL)
        matches = re.findall(
            r'href="(/en-us/article/[^"?]+)"[^>]*>.*?<(?:h2|h3|h4)[^>]*>(.*?)</(?:h2|h3|h4)>',
            page,
            flags=re.IGNORECASE | re.DOTALL,
        )
        news = []
        seen = set()
        for path, title in matches:
            title = re.sub(r"<[^>]+>", " ", title)
            title = html.unescape(re.sub(r"\s+", " ", title)).strip()
            if title and path not in seen:
                seen.add(path)
                news.append({"title": title, "url": "https://www.minecraft.net" + path})
            if len(news) == 4:
                break
        if news:
            return news
    except Exception:
        pass
    return [{"title": "暂时无法读取官方新闻，点击刷新重试", "url": MINECRAFT_NEWS_URL}]


def collect_data():
    manifest = api_status(
        "版本清单 API",
        VERSION_MANIFEST_URL,
        "Mojang launcher metadata",
        lambda payload: f"最新 {payload.get('latest', {}).get('release', 'unknown')}",
    )
    profile = api_status(
        "玩家档案 API",
        PROFILE_URL,
        "api.mojang.com",
        lambda payload: payload.get("name", "Notch"),
    )
    session = api_status(
        "会话服务 API",
        SESSION_URL,
        "sessionserver.mojang.com",
        lambda payload: payload.get("name", "profile"),
    )
    return {"apis": [manifest, profile, session], "news": collect_news(), "updated": time.strftime("%Y-%m-%d %H:%M:%S")}


def xaml_text(data):
    def esc(value):
        return html.escape(str(value), quote=True)

    api_items = []
    for item in data["apis"]:
        color = "#25B887" if item["state"] == "ONLINE" else "#D85C72"
        api_items.append(
            f'''<local:MyListItem Margin="-5,0,-5,7" Title="{esc(item["label"])} · {esc(item["state"])}" Info="{esc(item["detail"])}" />'''
        )
    news_items = []
    for item in data["news"]:
        news_items.append(
            f'''<local:MyListItem Margin="-5,0,-5,7" Title="{esc(item["title"])}" Info="Minecraft 官方新闻 · 点击标题打开原文" EventType="打开网页" EventData="{esc(item["url"])}" Type="Clickable" />'''
        )
    online_count = sum(item["state"] == "ONLINE" for item in data["apis"])
    return f'''<!-- Generated by realtime_home_server.py at {esc(data["updated"])} -->
<local:MyCard Title="HATSUNE MIKU · 01 / LIVE DATA" Margin="0,0,0,15">
    <Grid Margin="25,32,23,18">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="1.35*" />
            <ColumnDefinition Width="0.65*" MinWidth="220" />
        </Grid.ColumnDefinitions>
        <StackPanel Grid.Column="0" VerticalAlignment="Center">
            <TextBlock FontSize="12" FontWeight="Bold" Foreground="#00A7B5" Text="REALTIME MINECRAFT HOME / {online_count} OF 3 API ONLINE" />
            <TextBlock Margin="0,8,0,0" FontSize="26" FontWeight="Bold" Foreground="{{DynamicResource ColorBrush1}}" Text="欢迎回来，指挥官。" />
            <TextBlock Margin="0,8,12,0" FontSize="13" Foreground="{{DynamicResource ColorBrush2}}" Text="接口与新闻已经在主页内更新，不需要离开 PCL。" TextWrapping="Wrap" />
            <local:MyButton Margin="0,16,0,0" Height="38" Width="150" Padding="20,0,20,0" ColorType="Highlight" Text="刷新实时数据" EventType="刷新主页" />
        </StackPanel>
        <StackPanel Grid.Column="1" VerticalAlignment="Center" HorizontalAlignment="Center">
            <local:MyImage Height="175" Width="240" Source="https://ec.crypton.co.jp/img/vocaloid/mikuv3_img2.png" FallbackSource="https://box.moegirl.icu/media/thumb/MikuNewType_main.png/1200px-MikuNewType_main.png" />
            <TextBlock Margin="0,-5,0,0" HorizontalAlignment="Center" FontSize="11" Foreground="#00A7B5" Text="HATSUNE MIKU / CV01 / ONLINE" />
        </StackPanel>
    </Grid>
</local:MyCard>

<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="1.05*" />
        <ColumnDefinition Width="0.95*" />
    </Grid.ColumnDefinitions>
    <StackPanel Grid.Column="0" Margin="0,0,8,0">
        <local:MyCard Title="QUICK START · 快速启动" Margin="0,0,0,15" CanSwap="True" IsSwapped="False">
            <StackPanel Margin="25,40,23,18">
                <TextBlock Margin="0,0,0,12" Foreground="{{DynamicResource ColorBrush2}}" Text="选择一个入口，让今天的节拍先从这里响起。" />
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="1*" />
                        <ColumnDefinition Width="1*" />
                    </Grid.ColumnDefinitions>
                    <local:MyButton Grid.Column="0" Margin="0,0,10,0" Height="38" ColorType="Highlight" Text="启动游戏" EventType="启动游戏" EventData="\\current" />
                    <local:MyButton Grid.Column="1" Height="38" Text="内存优化" EventType="内存优化" />
                </Grid>
                <local:MyButton Margin="0,10,0,0" Height="38" Text="版本管理" EventType="切换页面" EventData="VersionSelect|Default" />
            </StackPanel>
        </local:MyCard>
        <local:MyCard Title="MY WORLDS · 最近使用的实例" Margin="0,0,0,15" CanSwap="True" IsSwapped="False">
            <StackPanel Margin="25,40,23,16">
                <local:MyListItem Margin="-5,0,-5,8" Logo="pack://application:,,,/images/Blocks/Grass.png" Title="MIKU SURVIVAL · 当前实例" Info="点击启动当前选中的 Minecraft 版本" EventType="启动游戏" EventData="\\current" Type="Clickable" />
                <local:MyListItem Margin="-5,0,-5,8" Logo="pack://application:,,,/images/Blocks/CommandBlock.png" Title="NEON CREATIVE · 创造测试" Info="建筑、红石与材质测试专用入口" EventType="切换页面" EventData="VersionSelect|Default" Type="Clickable" />
            </StackPanel>
        </local:MyCard>
        <local:MyCard Title="MIKU STATUS · 当前状态" Margin="0,0,0,15" CanSwap="True" IsSwapped="False">
            <StackPanel Margin="25,40,23,18">
                <local:MyHint Margin="0,0,0,10" Theme="Blue" Text="PCL HOME / REALTIME DATA READY" />
                <local:MyHint Margin="0,0,0,10" Theme="Yellow" Text="接口状态每 30 分钟自动更新，也可以手动刷新主页。" />
                <TextBlock FontSize="12" Foreground="{{DynamicResource ColorBrush2}}" Text="01 ONLINE    ·    MIKU BLUE    ·    WIDE MODE" />
            </StackPanel>
        </local:MyCard>
    </StackPanel>
    <StackPanel Grid.Column="1" Margin="8,0,0,0">
    <local:MyCard Title="MINECRAFT API · 当前接口状态" Margin="0,0,0,15">
        <StackPanel Margin="25,40,23,18">
            <TextBlock Margin="0,0,0,10" Foreground="{{DynamicResource ColorBrush2}}" Text="最后更新：{esc(data["updated"])}" />
            {''.join(api_items)}
            <local:MyHint Margin="0,8,0,0" Theme="Blue" Text="状态来自 Mojang 官方接口；点击上方按钮即可重新检测。" />
        </StackPanel>
    </local:MyCard>
    <local:MyCard Title="NEWS · Minecraft 最新新闻" Margin="0,0,0,15">
        <StackPanel Margin="25,40,23,18">
            <TextBlock Margin="0,0,0,10" Foreground="{{DynamicResource ColorBrush2}}" Text="来自 Minecraft 官方新闻页 · {esc(data["updated"])}" />
            {''.join(news_items)}
            <local:MyTextButton Margin="0,8,0,0" HorizontalAlignment="Center" Text="刷新新闻" EventType="刷新主页" />
        </StackPanel>
    </local:MyCard>
    </StackPanel>
</Grid>

<TextBlock Margin="0,5,0,18" HorizontalAlignment="Center" FontSize="11" Foreground="#00A7B5" Text="♪ 未来的声音，正在方块世界里继续播放。 ♪" />
'''


def live_xaml():
    now = time.time()
    if now - _cache["created"] < CACHE_SECONDS and _cache["payload"]:
        return _cache["payload"]
    payload = xaml_text(collect_data()).encode("utf-8")
    _cache["created"] = now
    _cache["payload"] = payload
    return payload


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path in ("/Custom.xaml", "/Custom.xaml/"):
            payload = live_xaml()
            self.send_response(200)
            self.send_header("Content-Type", "application/xaml+xml; charset=utf-8")
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(payload)
            return
        if self.path == "/Custom.xaml.ini":
            payload = live_xaml()
            version = hashlib.sha256(payload).hexdigest()[:16].encode("ascii")
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(version)
            return
        if self.path == "/health":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.end_headers()
            self.wfile.write(b"ok")
            return
        self.send_error(404)

    def log_message(self, format_string, *args):
        print(f"[{self.log_date_time_string()}] {format_string % args}")


def main():
    parser = argparse.ArgumentParser(description="Serve a live PCL Minecraft/Miku homepage")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--once", action="store_true", help="Generate a static Custom.xaml and exit")
    parser.add_argument("--output", default="Custom.xaml", help="Output path used with --once")
    args = parser.parse_args()
    if args.once:
        payload = live_xaml()
        with open(args.output, "wb") as output_file:
            output_file.write(payload)
        with open(args.output + ".ini", "w", encoding="ascii") as version_file:
            version_file.write(hashlib.sha256(payload).hexdigest()[:16])
        print(f"Generated {args.output}")
        return
    server = ThreadingHTTPServer((args.host, args.port), Handler)
    print(f"PCL realtime homepage: http://{args.host}:{args.port}/Custom.xaml")
    print("Press Ctrl+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
